add_newline = false
command_timeout = 500

format = """
$username$hostname$directory$git_branch$git_status$golang$nodejs$rust$kubernetes
$character
"""

[directory]
truncation_length = 3
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
disabled = false

[kubernetes]
disabled = false
format = "☸ [$context]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
